### ISSUE TITLE
Changing GitHub repo

### ISSUE THREAD

**Issue by lwaldron** [cmirzayi/EpiForBioWorkshop#9]
Note that moving the workshop to a new repo requires a change [here](https://github.com/Bioconductor/BioC2020/blob/15f2d89eda712266772fc7ffafd271ce6a22c845/docs/workshops.Rmd#L78) and [here](https://github.com/Bioconductor/BioC2020/blob/master/docs/workshops.md) (can be done by issue or better yet pull request).

**Comment by cmirzayi** [comment]
Pull request has been made with these changes.
